### ISSUE TITLE
gotk bootstrap and create helmrelease issue: context deadline exceeded with raspbernetes

### ISSUE THREAD

**Issue by jstewart612** [fluxcd/toolkit#372]
After following https://raspbernetes.github.io/docs/installation, I get constant context deadline exceeded errors including in the bootstrap and trying to add any helmreleases.

Here's the cli commands I ran:

`gotk bootstrap github --arch=arm64 --components=source-controller,kustomize-controller,helm-controller,notification-controller --owner=jstewart612 --path=raspbernetes --personal --repository=gotk --version=latest
gotk create source git monitoring --interval=30m --url=https://github.com/fluxcd/toolkit --branch=main
gotk create source helm stable --interval=1h --url=https://kubernetes-charts.storage.googleapis.com
gotk create helmrelease sealed-secrets --interval=1h --release-name=sealed-secrets --target-namespace=gotk-system --source=HelmRepository/stable --chart=sealed-secrets --chart-version="1.10.x"`

Logs:

[source-controller.txt](https://github.com/fluxcd/toolkit/files/5435379/source-controller.txt)
[notification-controller.txt](https://github.com/fluxcd/toolkit/files/5435380/notification-controller.txt)
[kustomize-controller.txt](https://github.com/fluxcd/toolkit/files/5435381/kustomize-controller.txt)
[helm-controller.txt](https://github.com/fluxcd/toolkit/files/5435382/helm-controller.txt)

**Comment by xUnholy** [comment]
@jstewart612 this isn't necessarily a gotk problem. It's because of the performance of the microSD disc IO and if you check other pods running across your cluster you'll see a lot of similar issues. This can be mitigated in the ansible scripts by increasing the etcd thresholds here https://github.com/raspbernetes/k8s-cluster-installation/blob/e8a72625824ea1198e09554707057d2a011292e5/ansible/group_vars/masters.yml#L18

I've set mine to 200 interval, 5000 timeout, this isn't perfect but if you're able to invest in getting a SSD to boot from you'll see massive performance benefits and you won't have this issue. You can follow this guide to do so: https://raspbernetes.github.io/docs/usb_booting

**Comment by jstewart612** [comment]
Confirmed issues to be I/O related:  because the error message just said "timeout" and not anything else, I didn't even think to check etcd, which is screaming timeouts all over the place.

Cheers @xUnholy ty I just got through converting to all SSDs in the cluster and it works great.  Not a gotk problem.
