### ISSUE TITLE
Multitenancy question

### ISSUE THREAD

**Issue by Perdjesk** [fluxcd/toolkit#93]
The current architecture of this new approach seems to assume that the "toolkit" controllers are running globally for all tenants (i.e assuming tenant are owning namespaces). 

### Diagram might be misleading
https://github.com/fluxcd/toolkit/blob/master/docs/diagrams/tk-feature.png

In this diagram "CRDs" are mentioned in a "tenant" box which I assume are namespaces. Whereas the custom objects boxes "Sources" and "Kustomizations" are outside of the tenant boxes. Reading the docs it is my understanding that it should be the reverse. The "CustomResourceDefinitions" are cluster level objects and should be out of a tenant box given that a tenant might not have cluster level permission to create them in a multi-tenancy model. The custom objects "Sources" and "Kustomizations" should be represented in the tenant box given the CRDs have scope "namespaced" and thus those are the objects that will be created by tenants within a namespace. Is this reasoning make sense?
See:
https://github.com/fluxcd/source-controller/blob/master/config/crd/bases/source.fluxcd.io_gitrepositories.yaml#L30
https://github.com/fluxcd/kustomize-controller/blob/master/config/crd/bases/kustomize.fluxcd.io_kustomizations.yaml#L27 

### Tenant isolation with shared controllers
In the context of a tenant owning a namespace without cluster level access that want to deploy to a specific namespace with private repository. 
My assumption would be that the tenant would be responsible to create one "Source" namespaced object with credentials and one "Kustomization" namespaced object referencing this "Source" object and the controller enforcing the permissions whether the "Kustomization" namespaces object has access to referenced "Source" object. Assuming as well that a namespaced "Kustomization" object has by default no permission and must explicitly reference a "serviceAccount" that is namespaced in the same namespace.

However by reading the following docs it seems that it is the responsibility of the admin to handle this for the tenants given the the "Kustomization" controller default to cluster admin access and admin are responsible to create "Kustomization" object scoped to a namespace. That seems to put a lot of legwork on the admins to handle this isolation for all tenants.
https://toolkit.fluxcd.io/components/kustomize/kustomization/#role-based-access-control

Wouldn't the previously described pattern possible in order to provide isolation between tenants fully managed by tenants themselves instead of relying on admin?
Is there currently any restrictions on which "sourceRef" can be used by "Kustomization" objects?

**Comment by stefanprodan** [comment]
The way we setup the control plane with `tk install/bootstrap` is for clusters where admins have to register sources and setup kustomizations for each team. A cluster user shouldn't have access to the `gitops-system` for this to work. 

> That seems to put a lot of legwork on the admins to handle this isolation for all tenants.

Yes this is the intention, to give sole ownership of sources and reconcilers SA to cluster admins.

> Is there currently any restrictions on which "sourceRef" can be used by "Kustomization" objects?

Yes, a Kustomization can reference a source only it the same namespace and since we setup source and kustomize controllers to only watch the namespace where they are deployed e.g. `gitops-system`, a user can't take over the cluster even if they create source or kustomization objects in their own repos/namespaces since no controller will act on them.

> Wouldn't the previously described pattern possible in order to provide isolation between tenants fully managed by tenants themselves instead of relying on admin?

Yes this could be possible if we setup the control plane like so:
- make source/kustomize controllers watch all namespaces by removing the RUNTIME_NAMESPACE env var
- write an admission controller that injects/overrides the SA in a Kustomization for non-admin namespaces (relies on having an allow-list of admin namespaces and service accounts)
